# Example configuration for connecting to a remote JMX server
spring:
  application:
    name: jmx-mcp-server-remote
  
  # Spring AI MCP Server Configuration
  ai:
    mcp:
      server:
        enabled: true
        name: "Remote JMX MCP Server"
        version: "1.0.0"
        type: SYNC
        instructions: "This server provides JMX monitoring and management capabilities for remote Java applications through MCP. Connect to remote JMX servers to monitor and manage distributed Java applications."
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: false
          completion: false

# JMX MCP Server configuration for remote connection
jmx:
  mcp:
    # Remote JMX Connection settings
    connection:
      type: REMOTE
      url: "service:jmx:rmi:///jndi/rmi://localhost:9999/jmxrmi"
      username: "admin"
      password: "password"
      timeout: 30s
      properties:
        # Additional JMX connection properties
        "jmx.remote.x.request.waiting.timeout": "10000"
        "jmx.remote.x.notification.fetch.timeout": "10000"
      
    # MBean Discovery settings for remote server
    discovery:
      include-patterns:
        - "java.lang:*"  # Include JVM MBeans
        - "com.myapp:*"  # Include application-specific MBeans
        - "org.apache.catalina:*"  # Include Tomcat MBeans if applicable
      exclude-patterns:
        - "java.util.logging:*"
        - "com.sun.management:*"
        - "*:type=RequestProcessor,*"  # Exclude noisy request processors
      refresh-interval: 60s  # Longer interval for remote connections
      discover-on-startup: true
      
    # Tools configuration
    tools:
      enabled: true
      prefix: "remote-jmx"
      max-parameters: 5  # Limit for remote operations
      exclude-operations:
        - "addNotificationListener"
        - "removeNotificationListener"
        - "dumpAllThreads"  # Potentially expensive operations
        
    # Resources configuration
    resources:
      enabled: true
      base-uri: "remote-jmx://"
      include-read-only: true
      include-write-only: false  # Safer for remote connections
      exclude-attributes:
        - "ObjectName"
        - "Verbose"  # Exclude potentially problematic attributes
        
    # Enhanced security for remote connections
    security:
      validate-parameters: true
      dangerous-operations:
        - "shutdown"
        - "restart"
        - "stop"
        - "destroy"
        - "gc"
        - "dumpHeap"
        - "resetStatistics"
      log-operations: true

# Logging configuration for remote monitoring
logging:
  level:
    org.jmxmcp: INFO
    org.springframework.ai.mcp: INFO
    javax.management.remote: WARN  # Reduce JMX remote logging noise
